# dataset general info
frame_path: JPEGImages/480p
flow_path: davis_test_flows
name2len: config/davis_name2len.pkl

flow:
  flow_height: 240
  flow_width: 432
  augments: False
  colors: RGB
  ext: .jpg

edge:
  sigma: 1
  low_threshold: 0.1
  high_threshold: 0.2
